#!/bin/sh
# Script para copiar TODOS los logos y configurar mwan3 y wireless, network al primer arranque
# Configuración personalizada de wireless
cat <<'EOF' > /etc/config/wireless
# Pon aquí tu configuración de wireless


config wifi-device 'radio0'
	option type 'mac80211'
	option path 'soc/11300000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0'
	option radio '0'
	option band '2g'
	option channel '6'
	option htmode 'EHT40'
	option country 'AE'
	option noscan '1'
	option rnr '1'
	option tx_burst '0.0'
	option cell_density '0'

config wifi-device 'radio1'
	option type 'mac80211'
	option path 'soc/11300000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0'
	option radio '1'
	option band '5g'
	option channel '100'
	option htmode 'EHT160'
	option country 'AE'
	option noscan '1'
	option rnr '1'
	option background_radar '1'
	option tx_burst '0.0'
	option cell_density '0'

config wifi-device 'radio2'
	option type 'mac80211'
	option path 'soc/11300000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0'
	option radio '2'
	option band '6g'
	option channel '37'
	option htmode 'EHT320'
	option country 'AE'
	option mbssid '1'
	option tx_burst '0.0'
	option cell_density '0'

config wifi-iface 'wifinet1'
	option device 'radio0'
	option mode 'ap'
	option ssid 'BANANA 2G'
	option encryption 'sae'
	option key '12345678'
	option ocv '0'
	option network 'lan'

config wifi-iface 'wifinet2'
	option device 'radio1'
	option mode 'ap'
	option ssid 'BANANA 5G'
	option encryption 'sae'
	option key '12345678'
	option ocv '0'
	option network 'lan'

config wifi-iface 'wifinet3'
	option device 'radio2'
	option mode 'ap'
	option ssid 'BANANA 6G'
	option encryption 'sae'
	option key '12345678'
	option ocv '0'
	option network 'lan'


# ... añade el resto de tu config personalizada ...
EOF
uci commit wireless

exit 0
